# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-name-based
#   annotations:
#     traefik.ingress.kubernetes.io/affinity: "true"
# spec:
#   rules:
#   - host: base.amordemaria.com
#     http:
#       paths:
#       - path: "/"
#         backend:
#           serviceName: mongo
#           servicePort: 27017
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: amordemaria.store
#     external-dns.alpha.kubernetes.io/ttl: "30"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /v1
#         pathType: Prefix
#         backend:
#           service:
#             name: angular
#             port:
#               number: 4200
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
  rules:
  - host: app.amordemaria.store
    http:
      paths:
      - path: "/"
        backend:
          serviceName: angular
          servicePort: 4200