apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-name-based
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
  rules:
  - host: base.amordemaria.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: mongo
          servicePort: 27017